title: MidTerm Project
description: Information on the finished Midterm project
theme: midterm

url: https://marks270.github.io/midtermproject/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
