title: MidTerm Project
description: Information on the finished Midterm project
theme: midterm

url: https://marks270.github.io/midtermproject/

aux_links:
  Template Repository: https://github.com/marks270/midtermproject
