title: MidTerm Project
description: Information on the finished Midterm project
theme: just-the-docs

url: https://marks270.github.io/midtermproject/

aux_links:
  Tinkercad: https://www.tinkercad.com/
